### ISSUE TITLE
Fix return cast values for php 8.1

### ISSUE THREAD

**Issue by MaximeSEM** [shoppingflux/php-sdk#108]
Hi,
We had a problem with 2 return types in PHP 8.1.
In OrderResource and ChannelResource the method getID() return an INT but values are biggest, so the result is truncated.
An example :
An order with the ID 17997529025 return 817659841
Can you remove the cast (int) ?

**Comment by mdumoulin** [comment]
This is not related to the PHP version but to PHP_INT_MAX. If you use a 32 bits OS, you can have this issue : https://www.php.net/manual/fr/reserved.constants.php#constant.php-int-max.

A solution could be to use a string instead of an int, but 32 bits OS are no longer frequently used anymore.

**Comment by mdumoulin** [comment]
This issue won't be fixed
