### ISSUE TITLE
Allow to send status update on order

### ISSUE THREAD

**Issue by ddattee** [shoppingflux/php-sdk#13]
I should be able to update orders status for those operation : accept, refuse, ship, refund.

Here is how I propose to do status update on order :
1. Add a templated link to the store : 
```json
"order": {
    "href": "/v1/store/{storeId}/order{/?operation}",
    "templated": true
}
```
2. Retrieve an updater from this link who will manage call to the order operations API
```php
<?php
/** @var \ShoppingFeed\Sdk\Api\Store\StoreResource $store */
$orderUpdater = $store->getOrderUpdater();
$orderUpdate  = new \ShoppingFeed\Sdk\Api\Order\OrderUpdate();

$orderUpdate->add('ref1', \ShoppingFeed\Sdk\Api\Order\OrderUpdate::ORDER_ACCEPT);
$orderUpdate->add('ref2', \ShoppingFeed\Sdk\Api\Order\OrderUpdate::ORDER_REFUSE);
$orderUpdate->add('ref3', \ShoppingFeed\Sdk\Api\Order\OrderUpdate::ORDER_CANCEL);
$orderUpdate->add('ref4', \ShoppingFeed\Sdk\Api\Order\OrderUpdate::ORDER_SHIP);

$orderUpdater->updateStatus($orderUpdate);
```

**Comment by ronan-gloo** [comment]
To my opinion, we should always keep the same organisation for ApI's:

- 1 API Object
- 1 Collection Object
- 1 Resource Object

So, the implementation should looks:

```php
<?php

$api  = $store->getOrderApi();
$api->newUpdateOperation()
  ->cancel('ref1')
  ->accept('ref2')
  ->accept('ref3')
  ->ship('ref4')
  ->execute();
```
This will prevent the user to explicit reference API constants, and provided clear and straight object api

**Comment by ddattee** [comment]
Something like this https://github.com/ddattee/php-sdk/pull/3 (just an exemple) ?
That allows to do this : 
```php
<?php
$inventoryApi = $store->getInventory();
$inventoryApi
    ->newInventoryUpdate()
    ->add('ref', 18)
    ->execute();
```

**Comment by ddattee** [comment]
@ronan-gloo  as discussed
Order operation execution will return a ticket collections that will allow to easily retrieve a ticket id for an order ref and get it's status :
```php
$ticketCollection = $updateOperations->execute();
$shipmentOperationStatus = $ticketCollection
    ->getShiped('orderRef')
    ->getStatus();
```
`getShiped` returns a ticket
`getStatus()` will call ticket endpoint and return a TicketStatus resource (when endpoint specified and created)
