### ISSUE TITLE
Allow to retreive number of new order from store

### ISSUE THREAD

**Issue by ddattee** [shoppingflux/php-sdk#15]
In order to get the number of new orders for a store I would add a method `getNewOrderCount()` to the store resource that will load the information stored in the embedded order resource.

**Comment by ronan-gloo** [comment]
This operation, in real, only report order created within last 24h. This is not a essential part of the SDK right now, count can be accessed from OrderCollection with appropriate filters.

**Comment by mdumoulin** [comment]
> This operation, in real, only report order created within last 24h. This is not a essential part of the SDK right now, count can be accessed from OrderCollection with appropriate filters.

Agree with this. We won't provide this information in Store resource.
