### ISSUE TITLE
Allow filter of orders by status

### ISSUE THREAD

**Issue by ddattee** [shoppingflux/php-sdk#18]
I should be able to filter order by status

**Comment by ronan-gloo** [comment]
Non, car on a une conservation de l'état entre deux calls, qui va provoquer des effets de bord.
C'est mieux de passer les contraintes en paramètres de fonction

**Comment by ddattee** [comment]
Ok directyl like this then :
```php
$filters = ['status' => 'shipped'];
foreach($orderDomain->getPages(1, 5, $filters) as $order) {
    // Will retrieve filtered items
}
```
