### ISSUE TITLE
Add continuous integration with Travis or Continuous PHP

### ISSUE THREAD

**Issue by ronan-gloo** [shoppingflux/php-sdk#2]
The continuous integration must automates execute builds for:

- Coding standards (https://www.php-fig.org/psr/psr-2/)
- Unit test (with PHPUnit, check #1 )
- Against PHP versions : 5.6.x, 7.0.x, 7.1.x, 7.2.x

@ddattee ready to discuss about this ;)

**Comment by ddattee** [comment]
I propose to add a `phing test` command that will run phpcs and phpunit see #9 for implementation.
