### ISSUE TITLE
Makes the SDK identification more accurate

### ISSUE THREAD

**Issue by ronan-gloo** [shoppingflux/php-sdk#61]
Require #60 to be merged !

The SDK should send requests with clear user-agent header, that:

- `SF-SDK-PHP/0.2.3 (PlatformName;PluginName)`
or
- `SF-SDK-PHP/0.2.3 (PlatformName)`

So, plugins should be able to be identified against the API, and eventually provides the store name to achieve better SF support.

Some exemples:

```php
<?php
$options->setUserAgentDetails('MyOwnShop', 'Magento 2.2');
$options->getUserAgent() // outputs `SF-SDK-PHP/0.2.3 (MyOwnShop;'Magento 2.2)`
```

**Comment by ddattee** [comment]
Resolved by https://github.com/shoppingflux/php-sdk/pull/62/files#diff-a839ae5659f16a864eafb8b1a9026427R193
