### ISSUE TITLE
Allow to retreive operation ticket status

### ISSUE THREAD

**Issue by ddattee** [shoppingflux/php-sdk#67]
After sending an order operation the SDK should allow to retrieve the task advancement state.

```php
...
$tickets = $orderApi->execute($operation);

foreach($tickets as $ticket) {
    echo $ticket->getStatus();  // outptut : running
    echo $ticket->getScheduledAt(); // output : 2018-12-02T12:00:00
    echo $ticket->getStartedAt(); // output : 2018-12-02T12:15:00
    echo $ticket->getFinishedAt();  // output : null
}
```

Which implies calling fetch ticket batch API and then fetch the ticket to retrieve status and dates.

**Comment by clement-hollander** [comment]
@ddattee we also should be allowed from a ticketID to retrieve the ticket

```php
$ticket = $ticketApi->getById('123-456');
echo $ticket->getStatus();
```

**Comment by mdumoulin** [comment]
> we also should be allowed from a ticketID to retrieve the ticket
> 
> ```
> $ticket = $ticketApi->getById('123-456');
> echo $ticket->getStatus();
> ```

This should be possible by default with `$ticket->getOne('123-456')`. Anyway, the initial issue has been solved. Please create a new issue if needed.
