### ISSUE TITLE
Implement tax amounts handling for order items

### ISSUE THREAD

**Issue by blmage** [shoppingflux/php-sdk#73]
Tax amounts for order items seem to be present in API results, but the corresponding `taxAmount` field is neither documented nor available from the [`OrderItem` class](https://github.com/shoppingflux/php-sdk/blob/master/src/Api/Order/OrderItem.php). Would it be possible to implement this?

For example, we would currently be needing this in order to detect whether tax should be applied to Amazon Business orders.

**Comment by ddattee** [comment]
Hi thanks for contacting us,

the `taxAmount` property is a recent addition to the API.
A task is in the pipe to add it to the SDK so be on the look out for a release very soon.

**Comment by ddattee** [comment]
we just released the `taxAmount` access in [v0.2.6](https://github.com/shoppingflux/php-sdk/releases/tag/0.2.6)

Enjoy !

**Comment by blmage** [comment]
Thanks for the update!
