### ISSUE TITLE
Incomplete addresses retrieving

### ISSUE THREAD

**Issue by kewix** [shoppingflux/php-sdk#75]
When using getBillingAddress() and getShippingAddress() I get incomplete data, do you know what is the problem ?
For example this is a dump of billing address : 
```
  array (
    'firstName' => '',
    'lastName' => '',
    'company' => '',
    'street' => '',
    'street2' => '',
    'other' => '',
    'postalCode' => '89450',
    'city' => 'ST PERE',
    'country' => 'FR',
    'phone' => '0',
    'mobilePhone' => '0',
    'email' => 'mpva+xxxxxxxxxxx@mp.laredoute-marketplace.fr',
  );
```

I'm using 0.2.4 version right now

Thanks for your help !

**Comment by ddattee** [comment]
Hi, thanks for contacting us.

What do you mean exactly by "incomplete data" ? 
The SDK is returning all data from [our API](https://developer.shopping-feed.com/order-api/order/v1store-orderfetch).

Regards,
David

**Comment by clement-hollander** [comment]
@kewix Laredoute only give addresses after the order has been accepted by the seller, that's why you see incomplete data
