### ISSUE TITLE
Implement fetching of reference aliases for order items (Order API)

### ISSUE THREAD

**Issue by blmage** [shoppingflux/php-sdk#86]
When a merchant updates an order item reference in his Shopping Feed back-office, the API does not directly mirror this change in the corresponding `items` field, but rather keeps track of the link between the old and new references under `itemsReferencesAliases`.

Currently, the value of this other field is not accessible via the [`OrderResource`](https://github.com/shoppingflux/php-sdk/blob/a8f42add1948e2c3b333538229cb1eb3f15ec15d/src/Api/Order/OrderResource.php#L7) class.

**Comment by ddattee** [comment]
Hi @blmage
We will look into this, but it shouldn't be a problem we will get back to you on this issue asap.
Thanks for the request

**Comment by ddattee** [comment]
Available in release 0.3.1 with #87
